gallery_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('gallery.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    # path('comments/', include('comments.urls')),
    path('moderation/', include('moderation.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

moderation/urls.py
from django.urls import path
from . import views
app_name = 'moderation'
urlpatterns = [
    path('', views.moderation_page, name='moderate'),
    path('api/categories/<int:category_id>/',
         views.update_category_api, name='update_category_api'),
    path('api/categories/delete/<int:category_id>/',
         views.delete_category_api, name='delete_category_api'),
    path('photo/<int:pk>/moderate/', views.moderate_photo, name='moderate_photo'),
    path('photo/<int:pk>/approve/', views.approve_photo, name='approve_photo'),
    path('user/<int:pk>/block/', views.block_user, name='block_user'),
    path('photo_list', views.photo_list, name='photo_list'),
    path('user_list', views.user_list, name='user_list'),
    path('user_detail/<int:pk>', views.user_detail, name='user_detail'),
]

users/urls.py
from django.urls import path
from .views import CustomLoginView
from . import views

app_name = 'users'
urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile_view, name='profile'),
]

moderation/models.py
from django.db import models
from gallery.models import Photo


class ModeratedPhoto(models.Model):
    photo = models.OneToOneField(Photo, on_delete=models.CASCADE)
    reason = models.TextField()
    moderated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Заблоковано: {self.photo.title}"

users/models.py
from django.contrib.auth.models import AbstractUser

from django.db import models


class CustomUser(AbstractUser):
    full_name = models.CharField(max_length=100)
    city = models.CharField(max_length=100, blank=True)
    country = models.CharField(max_length=100, blank=True)
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True)
    is_blocked = models.BooleanField(default=False)

moderation/forms.py
from django import forms
from gallery.models import Category
from .models import ModeratedPhoto


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Нова категорія', 'class': 'form-control'})
        }


class ModeratedPhotoForm(forms.ModelForm):
    class Meta:
        model = ModeratedPhoto
        fields = ['reason']
        widgets = {
            'reason': forms.Textarea(attrs={
                'rows': 4,
                'cols': 50,
                'placeholder': 'Причина блокування:',
                'class': 'form-control'
            }),
        }

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import CustomUser


class RegisterForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ['username', 'full_name', 'email', 'city',
                  'country', 'avatar', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-input'}),
            'full_name': forms.TextInput(attrs={'class': 'form-input'}),
            'email': forms.EmailInput(attrs={'class': 'form-input'}),
            'city': forms.TextInput(attrs={'class': 'form-input'}),
            'country': forms.TextInput(attrs={'class': 'form-input'}),
            'avatar': forms.ClearableFileInput(attrs={'class': 'form-input'}),
            # 'password' и 'password2' не нужно здесь указывать,
            # UserCreationForm уже управляет ими
        }


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': "Ім'я користувача"
        })
        self.fields['password'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Пароль'
        })

moderation/views.py
from django.shortcuts import render, redirect, get_object_or_404
from gallery.models import Category, Photo, CustomUser
from users.models import CustomUser
from .models import ModeratedPhoto
from django.contrib.admin.views.decorators import staff_member_required
from django.views.decorators.http import require_http_methods
from django.http import JsonResponse
import json
from .forms import CategoryForm, ModeratedPhotoForm
from django.db.models import Count


@staff_member_required
def moderation_page(request):
    print(request.user)
    total_photos = Photo.objects.count()
    total_users = CustomUser.objects.count()
    categories = Category.objects.all()
    form = CategoryForm()
    users_with_photo_counts = CustomUser.objects.annotate(
        uploaded_photo_count=Count('photo'))
    users_with_photo_counts = users_with_photo_counts.order_by(
        '-uploaded_photo_count')
    if request.method == 'POST':
        name = request.POST.get('name')
        if name:
            Category.objects.create(name=name)
            return redirect('moderation:moderate')
    return render(request, 'moderation/moderation_page.html', {'total_photos': total_photos,
                                                               'total_users': total_users,
                                                               'categories': categories,
                                                               'form': form,
                                                               'users_with_photo_counts': users_with_photo_counts
                                                               })


@staff_member_required
def update_category_api(request, category_id):
    try:
        category = get_object_or_404(Category, id=category_id)
        data = json.loads(request.body)
        new_name = data.get('name')

        if not new_name or not isinstance(new_name, str) or not new_name.strip():
            return JsonResponse({'message': "Ім'я категорії не може бути порожнім."}, status=400)

        category.name = new_name.strip()
        category.save()

        return JsonResponse({'id': category.id, 'name': category.name}, status=200)

    except json.JSONDecodeError:
        return JsonResponse({'message': 'Невірний формат JSON у тілі запиту.'}, status=400)
    except Exception as e:
        print(f"Ошибка при обновлении категории: {e}")
        return JsonResponse({'message': 'Внутрішня помилка сервера.'}, status=500)


@staff_member_required
@require_http_methods(["DELETE"])
def delete_category_api(request, category_id):
    try:
        category = get_object_or_404(Category, id=category_id)
        category_name = category.name
        category.delete()
        return JsonResponse(
            {'message': f'Категорія "{category_name}" успішно видалена.',
                'id': category_id},
            status=200
        )
    except Category.DoesNotExist: 
        return JsonResponse({'message': 'Категорія не знайдена.'}, status=404)
    except Exception as e:
        print(f"Ошибка при видаленні категории ID {category_id}: {e}")
        return JsonResponse({'message': 'Внутрішня помилка сервера при видаленні.'}, status=500)


@staff_member_required
def photo_list(request):
    photos = Photo.objects.all()
    return render(request, 'moderation/photo_list.html', {'photos': photos})


@staff_member_required
def moderate_photo(request, pk):
    photo = get_object_or_404(Photo, pk=pk)
    if request.method == 'POST':
        reason = request.POST.get('reason')
        moderated_entry = ModeratedPhoto.objects.filter(photo=photo).first()
        if not (moderated_entry):
            ModeratedPhoto.objects.create(photo=photo, reason=reason)
        photo.is_approved = False
        photo.save()
        return redirect('gallery:home')
    form = ModeratedPhotoForm()
    return render(request, 'moderation/moderate_photo.html', {'photo': photo, 'form': form})


@staff_member_required
def approve_photo(request, pk):
    try:
        photo = get_object_or_404(Photo, pk=pk)
        moderated_entry = ModeratedPhoto.objects.filter(photo=photo).first()
        if moderated_entry:
            try:
                moderated_entry.delete()
            except Exception as e:
                print(f'Помилка при видаленні ModeratedPhoto: {e}')
        photo.is_approved = True
        photo.save()
    except Exception as e:
        print('Помилка', e)
    return redirect('gallery:home')


@staff_member_required
def block_user(request, pk):
    user = get_object_or_404(CustomUser, pk=pk)
    if user.is_blocked == False:
        user.is_blocked = True
    else:
        user.is_blocked = False
    user.save()
    return redirect('moderation:user_list')


@staff_member_required
def user_list(request):
    users = CustomUser.objects.filter(is_staff=False)
    return render(request, 'moderation/user_list.html', {'users': users})


@staff_member_required
def user_detail(request, pk):
    try:
        user = get_object_or_404(CustomUser, pk=pk)
    except Exception as e:
        print(e)
    return render(request, 'moderation/detail_user.html', {'user': user})

users/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.urls import reverse_lazy
from .forms import RegisterForm, LoginForm


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('users:login')
    else:
        form = RegisterForm()
    return render(request, 'users/register.html', {'form': form})


def logout_view(request):
    logout(request)
    messages.success(request, 'Ви вийшли з акаунту.')
    return redirect('users:login')


@login_required
def profile_view(request):
    return render(request, 'users/profile.html', {'user': request.user})


class CustomLoginView(LoginView):
    template_name = 'users/login.html'
    authentication_form = LoginForm
    success_url = reverse_lazy('gallery:home')

    def form_valid(self, form):
        user = form.get_user()
        if user.is_blocked:
            return render(self.request, 'users/blocked.html', {})
        login(self.request, user)
        messages.success(self.request, f"Ласкаво просимо, {user.username}!")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(
            self.request, "Неправильне ім'я користувача або пароль. Будь ласка, спробуйте ще раз.")
        return super().form_invalid(form)

moderation/templates/moderation/categories.html
{% load crispy_forms_tags %}
<ul id= "category-list" class= "category-list-style" >
    {% for category in categories %}
        <li id="item-{{ category.id }}" data-item-id="{{ category.id }}" class="editable-item">
            <span class="item-display">{{ category.name }}</span> 
            <input type="text" class="item-input" value="{{ item.name }}" style="display: none;">
            <button type="button" class="btn btn-danger">Видалити</button>
        </li>
    {% endfor %}
</ul>
<form method="POST" class="category-list-style">
    {% csrf_token %}
    {{ form|crispy }} 

    <button type="submit" class="btn btn-success">Додати</button>
</form>

moderation/templates/moderation/detail_user.html
{% extends 'base.html' %}
{% block title %}Профіль{% endblock %}

{% block content %}
<div class="container mt-5"> 
    <div class="row justify-content-center"> 
        <div class="col-md-8 col-lg-6"> 
            <div class="card"> 
                <div class="card-header text-center">
                    <h3 class="mb-0">{{user.username}}</h3> 
                </div>
                <div class="card-body">
                    {% if user.avatar %}
                        <div class="text-center mb-4"> 
                            <img src="{{ user.avatar.url }}" alt="{{ user.username }} Avatar" class="img-fluid rounded-circle" style="width: 150px; height: 150px; object-fit: cover;">
                        </div>
                    {% else %}
                        <div class="text-center mb-4">
                            <img src="https://via.placeholder.com/150" alt="Default Avatar" class="img-fluid rounded-circle" style="width: 150px; height: 150px; object-fit: cover;"> {# Placeholder if no avatar #}
                        </div>
                    {% endif %}

                    <div class="mb-3">
                        <label class="form-label fw-bold">Користувач:</label>
                        <p class="form-control-plaintext">{{ user.username }}</p> 
                    </div>

                    <div class="mb-3">
                        <label class="form-label fw-bold">Email:</label>
                        <p class="form-control-plaintext">{{ user.email }}</p>
                    </div>

                    {% if user.full_name %}
                    <div class="mb-3">
                        <label class="form-label fw-bold">Повне ім'я:</label>
                        <p class="form-control-plaintext">{{ user.full_name }}</p>
                    </div>
                    {% endif %}

                    {% if user.city %}
                    <div class="mb-3">
                        <label class="form-label fw-bold">Місто:</label>
                        <p class="form-control-plaintext">{{ user.city }}</p>
                    {% endif %}
                    
                    {% if user.country %}
                    <div class="mb-3">
                        <label class="form-label fw-bold">Країна:</label>
                        <p class="form-control-plaintext">{{ user.country }}</p>
                    {% endif %}
                    <div class="mb-3">
                        <label class="form-label fw-bold">Дата створення аккаунта:</label>
                        <p class="form-control-plaintext">{{ user.date_joined }}</p>
                    <div class="mb-3">
                        <label class="form-label fw-bold">Заблокований:</label>
                        <p class="form-control-plaintext">{{ user.is_blocked }}</p>
                    <div class="mb-3">
                        <label class="form-label fw-bold">Не вимкненый аккаунт:</label>
                        <p class="form-control-plaintext">{{ user.is_active }}</p>


{% endblock %}

moderation/templates/moderation/moderate_photo.html
{% extends "base.html" %}
{% block title %}модерація фото{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<h2>Модерація фото: {{ photo.title }}</h2>
<img src="{{ photo.image.url }}" alt="{{ photo.title }}" width="400">
<form method="POST">
    {% csrf_token %}
    {{ form|crispy }} 
    <button type="submit" class="btn btn-danger">Заблокувати</button>
</form>
{% endblock %}

moderation/templates/moderation/moderation_page.html
{%extends 'base.html'%}
{%load static%}
{%block content%}

<div class="container mt-4"> 
       <div class="row align-items-center mb-4">
    <div class="col-auto ps-0"> <h1 class="mb-0 ">Панель Модерації</h1> </div>
    <div class="col-auto ms-4"> <a class="nav-link" href="/moderation/photo_list">Список фото</a>
    </div>
    <div class="col-auto ms-3"> <a class="nav-link" href="/moderation/user_list">Список користувачів</a>
    </div>
</div>
</div>
        <div class="row mb-5">
            <div class="col-md-6 mb-3"> 
            <h2 class="mt-0 mb-3">Статистика</h2>
                <div class="card shadow-sm p-3 h-100"> 
                    {% include 'moderation/statistics.html' %}
                </div>
            </div>
            <div class="col-md-6 mb-3">
                <h2 class="mt-0 mb-3">Управління категоріями</h2>
                <div class="card shadow-sm p-3 h-100"> 
                    {% include 'moderation/categories.html' %}
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'js/admin/categories.js' %}"></script>

{% endblock %}

moderation/templates/moderation/photo_list.html
{% extends 'base.html' %}
{% block title %}Модерація Фото{% endblock %}
{% block content %}
<h2>Фото на модерації</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Превʼю</th>
            <th>Назва</th>
            <th>Автор</th>
            <th>Опис</th>
            <th>Дії</th>
        </tr>
    </thead>
    <tbody>
        {% for photo in photos %}
        <tr>
            <td><img src="{{ photo.image.url }}" width="100"></td>
            <td>{{ photo.title }}</td>
            <td>{{ photo.author.username }}</td>
            <td>{{ photo.description|truncatechars:50 }}</td>
            <td>
                <a href="/moderation/photo/{{photo.id}}/approve/" class="btn btn-success btn-sm">✅</a>
                <a href="/moderation/photo/{{photo.id}}/moderate/" class="btn btn-danger btn-sm">🗑️</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

moderation/templates/moderation/statistics.html
<div class="statistics-content">
    <div class="row mb-3">
        <div class="col-6">
            <h5 class="card-subtitle mb-2 text-muted">Користувачів:</h5>
            <p class="card-text fs-4 fw-bold">{{ total_users }}</p>
        </div>
        <div class="col-6">
            <h5 class="card-subtitle mb-2 text-muted">Фотографій:</h5>
            <p class="card-text fs-4 fw-bold">{{ total_photos }}</p>
        </div>
    </div>

    <h5 class="card-subtitle mb-2 text-muted">Категорії:</h5>
    <ul class="list-group list-group-flush">
        {% for cat in categories %}
            <li class="list-group-item d-flex justify-content-between align-items-center py-1 ps-0 pe-0">
                <span class="category-name me-2">{{ cat.name }}</span>

                <span class="badge bg-secondary rounded-pill">{{ cat.photo_count }} фото</span>
            </li>
        {% endfor %}
    </ul>
    <h5 class="card-subtitle mb-2 text-muted">Топ користувачів за фото:</h5>
    <ul class="list-group list-group-flush">
        {% for user in users_with_photo_counts %}
            <li class="list-group-item d-flex justify-content-between align-items-center py-1 ps-0 pe-0">
                <span class="user-name me-2">{{ user.username }}</span>
                <span class="badge bg-primary rounded-pill">{{ user.uploaded_photo_count }} фото</span> 
            </li>
        {% endfor %}
    </ul>
      </div>

moderation/templates/moderation/user_list.html
{% extends 'base.html' %}

{% block title %}Модерація Користувачів{% endblock %}

{% block content %}
<h2>Користувачі</h2>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Ім'я користувача</th>
            <th>Email</th>
            <th>Активний</th>
            <th>Персонал</th>
            <th>Дата реєстрації</th>
            <th>Дії</th>
        </tr>
    </thead>
    <tbody>
        {% for user in users %}
        <tr>
            <td>{{ user.id }}</td>
            <td>{{ user.username }}</td>
            <td>{{ user.email }}</td>
            <td>{% if user.is_active %}Так{% else %}Ні{% endif %}</td>
            <td>{% if user.is_staff %}Так{% else %}Ні{% endif %}</td>
            <td>{{ user.date_joined|date:"d.m.Y H:i" }}</td> 
            <td>
                
                <a href="/moderation/user_detail/{{user.id}}" class="btn btn-warning btn-sm">Деталі</a> 
                {% if user.is_blocked %}
                    <a href="/moderation/user/{{user.id}}/block/" class="btn btn-success btn-sm">Розблокувати</a> 
                {% else %}
                    <a href="/moderation/user/{{user.id}}/block/" class="btn btn-danger btn-sm">Блокувати</a> 
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

moderation/templates/moderation/users.html
{{% extends "base.html" %}}
{% block title %}Категорії{% endblock %}
{% block content %}
<h2>Користувачі</h2>
<ul>
{% for user in users %}
    <li>
    {{ user.username }} - {% if user.is_blocked %}Заблокований
    {% else %}
        <a href="{% url 'moderation:block_user' user.pk %}" class="btn btn-warning">Заблокувати</a>
    {% endif %}
    </li>
{% endfor %}
</ul>
{% endblock %}