gallery_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('gallery.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    # path('comments/', include('comments.urls')),
    path('moderation/', include('moderation.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import CustomLoginView
from . import views

app_name = 'users'
urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile_view, name='profile'),
]

templates/base.html
<!-- templates/base.html -->
{%load static%}
<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Фото Галерея{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    {% block extra_head %}{% endblock %}
</head>
<body>
    {% include "navbar.html" %}
    <main class="container mt-4">
        {% block content %}{% endblock %}
    </main>
    {% include "footer.html" %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    {% block extra_js %}{% endblock %}
</body>
</html>

templates/footer.html
<footer class="bg-light text-center py-3 mt-4">
    <p class="mb-0">&copy; 2025 Фото Галерея Онлайн</p>
</footer>

templates/navbar.html
<!-- templates/navbar.html -->
 {%load static%}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="/">Галерея</a>
        
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                    {% if user.is_staff%}
                        <li class="nav-item"><a class="nav-link" href="/moderation">Модерація</a></li>
                    {% endif %} 
                    <li class="nav-item"><a class="nav-link" href="/upload/">Завантажити</a></li>
                    <li class="nav-item"><a class="nav-link" href="/users/profile/">Профіль</a></li>
                    <li class="nav-item"><form method="post" action="{% url 'users:logout' %}">
                                            {% csrf_token %}
                                            <button type="submit"  class="no-style-button">Выйти</button>
                                        </form></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="/users/login/">Увійти</a></li>
                    <li class="nav-item"><a class="nav-link" href="/users/register/">Реєстрація</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>